#!/usr/bin/env bash
set -ue
shopt -s lastpipe

if [ $# -eq 0 ]; then
  ACTION=$(
         cat << EOF | fzf --prompt="gh gist > " --height=40%
clone
delete
edit
view
EOF
  )
  if [ -z "$ACTION" ]; then
      exit 1
  fi
else
  ACTION=$1
fi

GIST=$(gh gist list --limit 1000 | fzf --prompt="gh gist $ACTION > " --height=40% --preview="echo {} | awk '{print \$1}' | xargs -n 1 gh gist view" | awk '{print $1}')

if [ -z "$GIST" ]; then
    exit 127
fi

gh gist "$ACTION" "$GIST"
